#!/bin/bash


# Reading-in Version and Build Number 

echo -e "\x1B[01;92m Welcome to Zynga's Automated Testing System!!\x1B[0m" 

sleep 1

echo -e "\x1B[01;92m What is the Build Number?\x1B[0m"

read BuildNumber

export BuildNumber

	# Removing old files from previous test 
		rm null
		rm Result.txt
		rm -rf ImageTests/ActualPics/*

./Unlock

./NewVersion

./AppStart

./AppFtue

./AppLogin

./HelpScreen

./NewGameScreen

./EmailResults 

