#!/bin/bash


# Email Results to Tester

echo -e "\x1B[01;92m Test Completed! \x1B[0m" 

echo -e "\x1B[01;92m Would you like a copy of the results emailed to the Zynga QA Email Account? (y/n) \x1B[0m" 

read input

if [ "$input" == 'y' ]; then

	echo "" | mutt -a "Result.txt" -s "Automated Test Results for Build# $BuildNumber" -- qa.zynga123@gmail.com
	echo -e "\x1B[01;92m Email Sent! Thank you.\x1B[0m"

else

	echo -e "\x1B[01;92m Thank you for using the system.\x1B[0m"
	sleep 1
	exit

fi