#!/bin/bash

# Opening Settings Menu (Swiping Left)

sleep 3
adb shell input swipe 200 940 985 940 


		# Checking if Settings Menu Opens Properly (screenshot without coins and banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualSettingsPage.bmp
				convert ActualSettingsPage.bmp -crop 1080x1560+0+75 $img "ActualSettingsPage.bmp";
				mv ActualSettingsPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Settings page Picture

					if compare -metric MAE /Users/shashmani/Desktop/WTPScript/ImageTests/ActualPics/ActualSettingsPage.bmp /Users/shashmani/Desktop/WTPScript/ImageTests/TestImages/SettingsPage.bmp null; 
						then
								echo -e "\x1B[01;92m Test 6: Settings Page Opens Correctly.\x1B[0m" 
								echo "Test 6: Settings Page Opens Correctly."  >> Result.txt
								say "Test 6 Passed!"
							else
								echo -e "\x1B[31m Test 6: FAILED - Settings Page did not open properly. \x1B[0m"  
								echo "Test 6: FAILED - Settings Page did not open properly." >> Result.txt 
								say "Test 6 Failed!"
					fi



# Opening Options Menu 

adb shell input tap 600 450 


		# Checking if Options Menu Opens Properly (screenshot without coins and banner - NOTE: This will only work as long as the volume is MAX) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualOptionsPage.bmp
				convert ActualOptionsPage.bmp -crop 1080x1560+0+75 $img "ActualOptionsPage.bmp";
				mv ActualOptionsPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Options Screen Picture

					if compare -metric MAE /Users/shashmani/Desktop/WTPScript/ImageTests/ActualPics/ActualOptionsPage.bmp /Users/shashmani/Desktop/WTPScript/ImageTests/TestImages/OptionsPage.bmp null; 
						then
								echo -e "\x1B[01;92m Test 7: Options Page Opens Correctly.\x1B[0m"  
								echo "Test 7: Options Page Opens Correctly." >> Result.txt
								say "Test 7 Passed!"
							else
								echo -e "\x1B[31m Test 7: FAILED - Options Page Page did not open properly. \x1B[0m"  
								echo "Test 7: FAILED - Options Page Page did not open properly." >> Result.txt 
								say "Test 7 Failed!"
					fi



				# Going back to settings menu 
				adb shell input keyevent 4


# Opening Account Menu (HAVE TO WORK ON THIS....)

adb shell input tap 600 650
sleep 1


		# Checking if Account Menu Opens Properly (screenshot without coins and banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualAccountPage.bmp
				convert ActualAccountPage.bmp -crop 1080x1560+0+75 $img "ActualAccountPage.bmp";
				mv ActualAccountPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Account Settings Page Picture

					if compare -metric MAE /Users/shashmani/Desktop/WTPScript/ImageTests/ActualPics/ActualAccountPage.bmp /Users/shashmani/Desktop/WTPScript/ImageTests/TestImages/AccountPage.bmp null; 
						then
								echo -e "\x1B[01;92m Test 8: Account Page Opens Correctly.\x1B[0m"
								echo "Test 8: Account Page Opens Correctly." >> Result.txt
								say "Test 8 Passed!"
							else
								echo -e "\x1B[31m Test 8: FAILED - Account Page did not open properly. \x1B[0m"
								echo "Test 8: FAILED - Account Page did not open properly." >> Result.txt 
								say "Test 8 Failed!"
					fi


				# Going back to settings menu 
				adb shell input keyevent 4



# Opening Help Menu

adb shell input tap 600 820
sleep 2


		# Checking if Help Menu Opens Properly (screenshot without coins and banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualHelpPage.bmp
				convert ActualHelpPage.bmp -crop 1080x1860+0+75 $img "ActualHelpPage.bmp";
				mv ActualHelpPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Account Settings Page Picture

					if compare -metric MAE /Users/shashmani/Desktop/WTPScript/ImageTests/ActualPics/ActualHelpPage.bmp /Users/shashmani/Desktop/WTPScript/ImageTests/TestImages/HelpPage.bmp null; 
						then
								echo -e "\x1B[01;92m Test 9: Help Menu Opens Correctly.\x1B[0m"
								echo "Test 9: Help Menu Opens Correctly."  >> Result.txt
								say "Test 9 Passed!"
							else
								echo -e "\x1B[31m Test 9: FAILED - Help Menu did not open properly. \x1B[0m" 
								echo "Test 9: FAILED - Help Menu did not open properly." >> Result.txt 
								say "Test 9 Failed!"
					fi

				# Going back to settings menu 
				adb shell input keyevent 4

				# Going back to game home-screen 
				adb shell input swipe 985 940 200 940 

