#!/bin/bash

# Open app

 adb shell am start -n com.zynga.gswf/.ui.launch.GameshowMainActivity 

 	#Checking if App Starts Properly

		sleep 1
		adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualAppOpen.bmp
		convert ActualAppOpen.bmp -crop 1080x1860+0+75 $img "ActualAppOpen.bmp";
		mv ActualAppOpen.bmp ImageTests/ActualPics

			# Comparing Actual Screenshot to Stored App_Open_Screen Picture

			if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/ActualAppOpen.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/AppOpenPage.bmp null; 
				then
						echo -e "\x1B[01;92m Test 1: The app successfully downloaded, installed and opened correctly."  
						echo "Automated Test Results for Build# $BuildNumber" >> Result.txt
						echo "Test 1: The app successfully downloaded, installed and opened correctly." >> Result.txt
						say "Test 1 Passed!"
					else
						echo -e "\x1B[31m Test 1: FAILED - The app did not open properly. \x1B[0m"  
						echo "Test 1: FAILED - The app did not open properly." >> Result.txt 
						say "Test 1 Failed!"
			fi





