#!/bin/bash

# Opening Settings Menu (Swiping Left)

sleep 3
adb shell input swipe 200 940 985 940 


		# Checking if Settings Menu Opens Properly (screenshot without banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualSettingsPage.bmp
				convert ActualSettingsPage.bmp -crop 1080x1695+0+75 $img "ActualSettingsPage.bmp";
				mv ActualSettingsPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Settings page Picture

					if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/ActualSettingsPage.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/SettingsPage.bmp null; 
						then
								echo -e "\x1B[01;92m PASS - Test 8: Settings Page Opens Correctly.\x1B[0m" 
								echo "Test 8: PASS - Settings Page Opens Correctly."  >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt
								say "Test 8 Passed!"
							else
								echo -e "\x1B[31m Test 8: FAILED - Settings Page did not open properly. \x1B[0m"  
								echo "Test 8: FAILED - Settings Page did not open properly." >> ScriptResults/Result_Build#$BuildNumber.txt 
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt 
								say "Test 8 Failed!"
					fi



# Opening Options Menu 

adb shell input tap 600 450 


		# Checking if Options Menu Opens Properly (screenshot without banner - NOTE: This will only work as long as the volume is MAX) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualOptionsPage.bmp
				convert ActualOptionsPage.bmp -crop 1080x1695+0+75 $img "ActualOptionsPage.bmp";
				mv ActualOptionsPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Options Screen Picture

					if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/ActualOptionsPage.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/OptionsPage.bmp null; 
						then
								echo -e "\x1B[01;92m PASS - Test 9: Options Page Opens Correctly.\x1B[0m"  
								echo "Test 9: PASS - Options Page Opens Correctly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt
								say "Test 9 Passed!"
							else
								echo -e "\x1B[31m Test 9: FAILED - Options Page Page did not open properly. \x1B[0m"  
								echo "Test 9: FAILED - Options Page Page did not open properly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt 
								say "Test 9 Failed!"
					fi



				# Going back to settings menu 
				adb shell input keyevent 4


# Opening Account Menu and Changing Password 

adb shell input tap 600 650
sleep 1
adb shell input tap 670 950
sleep 0.5
adb shell input text zynga12345
sleep 0.5
adb shell input tap 975 1830
sleep 0.5
adb shell input text zynga12345
sleep 0.5
adb shell input tap 975 1830
sleep 0.5
adb shell input tap 600 1150
sleep 1


		# Checking if Account Menu Opens and Changes can be saved Properly (screenshot without banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > AccountChanges.bmp
				convert AccountChanges.bmp -crop 1080x1695+0+75 $img "AccountChanges.bmp";
				mv AccountChanges.bmp ImageTests/ActualPics				

				#Comparing Actual Screenshot to Stored Settings Page Picture

					if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/AccountChanges.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/SettingsPage.bmp null; 
						then
								echo -e "\x1B[01;92m PASS - Test 10: Account Page Opens and Changes can be Saved Correctly.\x1B[0m"
								echo "Test 10: PASS - Account Page Opens and Changes can be Saved Correctly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt
								say "Test 10 Passed!"
							else
								echo -e "\x1B[31m Test 10: FAILED - Account Page did not open or Changes were not Saved properly. \x1B[0m"
								echo "Test 10: FAILED - Account Page did not Open or Changes were not Saved properly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt 
								say "Test 10 Failed!"
					fi


# Opening Help Menu

adb shell input tap 600 820
sleep 3


		# Checking if Help Menu Opens Properly 
				sleep 2
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualHelpPage.bmp
				convert ActualHelpPage.bmp -crop 1080x1860+0+75 $img "ActualHelpPage.bmp";
				mv ActualHelpPage.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored Account Settings Page Picture

					if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/ActualHelpPage.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/HelpPage.bmp null; 
						then
								echo -e "\x1B[01;92m PASS - Test 11: Help Menu Opens Correctly.\x1B[0m"
								echo "Test 11: PASS - Help Menu Opens Correctly."  >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt
								say "Test 11 Passed!"
							else
								echo -e "\x1B[31m Test 11: FAILED - Help Menu did not open properly. \x1B[0m" 
								echo "Test 11: FAILED - Help Menu did not open properly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt 
								say "Test 11 Failed!"
					fi

				# Going back to settings menu 
				adb shell input keyevent 4

				# Going back to game home-screen 
				adb shell input swipe 985 940 200 940 

