#!/bin/bash

# Starting a new game ("Start a Game!" Button)

sleep 1
adb shell input tap 575 340

		# Checking if New Game Screen Opens Properly (Following screenshot without banner) 
				sleep 1
				adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > ActualNewGameScreen.bmp
				convert ActualNewGameScreen.bmp -crop 1080x1695+0+75 $img "ActualNewGameScreen.bmp";
				mv ActualNewGameScreen.bmp ImageTests/ActualPics

					#Comparing Actual Screenshot to Stored New Game Screen Picture

					if compare -metric MAE /Users/shashmani/Desktop/Script/WTPScript/ImageTests/ActualPics/ActualNewGameScreen.bmp /Users/shashmani/Desktop/Script/WTPScript/ImageTests/TestImages/NewGameScreen.bmp null; 
						then
								echo -e "\x1B[01;92m PASS - Test 14: New Game Screen Opens Correctly. \x1B[0m" 
								echo "Test 14: PASS - New Game Screen Opens Correctly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt
								say "Test 14 Passed!"
							else
								echo -e "\x1B[31m Test 14: FAILED - New Game Screen did not open properly. \x1B[0m"
								echo "Test 14: FAILED - New Game Screen did not open properly." >> ScriptResults/Result_Build#$BuildNumber.txt  
								echo "" >> ScriptResults/Result_Build#$BuildNumber.txt 
								say "Test 14 Failed!"
					fi


